framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            friend_request_messages:
                dsn: '%env(MESSENGER_TRANSPORT_FRIEND_REQUEST_EXCHANGE_DSN)%'
                options:
                    auto_setup: true
                    exchange:
                        name: friend_request_exchange
                        default_publish_routing_key: friend_request_key
                    queues:
                        friend_request_queue:
                            binding_keys: [friend_request_key]

            email_messages:
                dsn: '%env(MESSENGER_TRANSPORT_EMAIL_MESSAGES_DSN)%'
                options:
                    auto_setup: true
                    exchange:
                        name: email_messages
                        default_publish_routing_key: email_key
                    queues:
                        email_queue:
                            binding_keys: [email_key]

            set_type_messages:
                dsn: '%env(MESSENGER_TRANSPORT_SET_TYPE_DSN)%'
                options:
                    auto_setup: true
                    exchange:
                        name: set_type_messages
                        default_publish_routing_key: set_type_key
                    queues:
                        set_type_queue:
                            binding_keys: [ set_type_key ]

            raw_log: '%env(REDIS_URL)%/2'
#            raw_log:
#                dsn: '%env(REDIS_URL)%/2'
#                options:
#                    auto_setup: true

        routing:
            # Route your messages to the transports
            'App\Message\EmailMessage': email_messages
            'App\Message\UserFriendRequestMessage': friend_request_messages
            'App\Message\NotificationMethodMessage': set_type_messages
            'App\Util\RawLogBuffer\PersistService\DTO\BufferLogMessage': raw_log

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
