framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            friend_request_messages:
                dsn: '%env(MESSENGER_TRANSPORT_FRIEND_REQUEST_EXCHANGE_DSN)%'
                options:
                    auto_setup: true
                    exchange:
                        name: friend_request_exchange
                        default_publish_routing_key: friend_request_key
                    queues:
                        friend_request_queue:
                            binding_keys: [friend_request_key]

            email_messages:
                dsn: '%env(MESSENGER_TRANSPORT_EMAIL_MESSAGES_DSN)%'
                options:
                    auto_setup: true
                    exchange:
                        name: email_messages
                        default_publish_routing_key: email_key
                    queues:
                        email_queue:
                            binding_keys: [email_key]

        routing:
            # Route your messages to the transports
            'App\Message\EmailMessage': email_messages
            'App\Message\UserFriendRequestMessage': friend_request_messages

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
