snc_redis:
    clients:

# Define your clients here. The example below connects to database 0 of the default Redis server.
#
# See https://github.com/snc/SncRedisBundle/blob/master/docs/README.md for instructions on
# how to configure the bundle.
#
    # db number 0 is default for snc redis bundle
        default:
            type: phpredis
            alias: default
            dsn: "%env(REDIS_URL)%/0"

        # db number 1 is used as entity doctrine entity logging buffer
        entity_log:
            type: phpredis
            dsn: "%env(REDIS_URL)%/1"

        # db number 2 is used as raw log buffer
        raw_log:
            type: phpredis
            dsn: "%env(REDIS_URL)%/2"

        # db number 3 is used as app cache
        app_cache:
            type: phpredis
            dsn: "%env(REDIS_URL)%/3"
