version: "3.8"

services:
  nginx:
    image: nginx:1.23
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/ok
      - ./.docker/nginx/localhost.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - php
    networks:
      - local_network

  php:
    build: ./.docker/php
    container_name: php
    restart: unless-stopped
    working_dir: /var/www/ok
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/ok
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      APP_ENV: dev
      PHP_IDE_CONFIG: "serverName=Project"
      XDEBUG_SESSION: PHPSTORM
    networks:
      - local_network
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:alpine
    restart: on-failure
    ports:
      - "16379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    networks:
      - local_network

  db:
    image: postgres:15.4
    container_name: postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:15432:5432"
    environment:
      POSTGRES_DB: ok
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./.docker/db/pgsql.conf:/etc/postgresql/postgresql.conf
      - ./.docker/db/init:/docker-entrypoint-initdb.d
    networks:
      - local_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 2s
      timeout: 20s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - local_network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - local_network

volumes:
  db_data:
  redis_data:

networks:
  local_network:
    driver: bridge
