<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240501195707 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create logs table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE logs (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            level VARCHAR(255) NOT NULL,
            channel VARCHAR(255) NOT NULL,
            datetime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            message VARCHAR(512) NOT NULL,
            context JSON NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('COMMENT ON COLUMN logs.datetime IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX IDX_LOGS_LEVEL_CHANNEL_DATETIME ON logs (level, channel, datetime)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql(
            'DROP INDEX IDX_LOGS_LEVEL_CHANNEL_DATETIME ON logs',
        );
        $this->addSql('DROP TABLE logs');
    }
}
