<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240401155455 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_friends (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            user_id INT NOT NULL,
            friend_id INT NOT NULL,
            PRIMARY KEY(id)
        )');

        $this->addSql('CREATE INDEX IDX_USER_ID ON user_friends (user_id)');
        $this->addSql('CREATE INDEX IDX_FRIEND_ID ON user_friends (friend_id)');

        $this->addSql('ALTER TABLE user_friends 
            ADD CONSTRAINT IDX_USER_ID FOREIGN KEY (user_id) REFERENCES "user" (id) 
                NOT DEFERRABLE INITIALLY IMMEDIATE
        ');
        $this->addSql('ALTER TABLE user_friends 
            ADD CONSTRAINT IDX_FRIEND_ID FOREIGN KEY (friend_id) REFERENCES "user" (id) 
                NOT DEFERRABLE INITIALLY IMMEDIATE
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE user_friends');
    }
}
